apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{"meta.helm.sh/release-name":"jenkins","meta.helm.sh/release-namespace":"jenkins"},"creationTimestamp":"2026-01-21T03:09:22Z","generation":3,"labels":{"app.kubernetes.io/component":"jenkins-controller","app.kubernetes.io/instance":"jenkins","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"jenkins","helm.sh/chart":"jenkins-5.8.115"},"name":"jenkins","namespace":"jenkins","resourceVersion":"7347936","uid":"37cbc16f-3bb0-49e9-8fe3-e7792e967c9e"},"spec":{"persistentVolumeClaimRetentionPolicy":{"whenDeleted":"Retain","whenScaled":"Retain"},"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"jenkins-controller","app.kubernetes.io/instance":"jenkins"}},"serviceName":"jenkins","template":{"metadata":{"annotations":{"checksum/config":"f93b0dce2d1985a938deaddcec93eb3b695745dc7790dcb961329173f7b48051","kubectl.kubernetes.io/restartedAt":"2026-01-21T02:36:02Z"},"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"jenkins-controller","app.kubernetes.io/instance":"jenkins","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"jenkins","helm.sh/chart":"jenkins-5.8.115"}},"spec":{"automountServiceAccountToken":true,"containers":[{"args":["--httpPort=8080"],"env":[{"name":"SECRETS","value":"/run/secrets/additional"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"JAVA_OPTS","value":"-Dcasc.reload.token=$(POD_NAME) "},{"name":"JENKINS_OPTS","value":"--webroot=/var/jenkins_cache/war "},{"name":"JENKINS_SLAVE_AGENT_PORT","value":"50000"},{"name":"CASC_JENKINS_CONFIG","value":"/var/jenkins_home/casc_configs"}],"image":"harbor.lab.local/jenkins/maven-agent:17","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/login","port":"http","scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"jenkins","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"},{"containerPort":50000,"name":"agent-listener","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/login","port":"http","scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"50m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true,"runAsGroup":1000,"runAsUser":1000},"startupProbe":{"failureThreshold":12,"httpGet":{"path":"/login","port":"http","scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"},{"mountPath":"/var/jenkins_config","name":"jenkins-config","readOnly":true},{"mountPath":"/usr/share/jenkins/ref/plugins/","name":"plugin-dir"},{"mountPath":"/var/jenkins_home/casc_configs","name":"sc-config-volume"},{"mountPath":"/run/secrets/additional","name":"jenkins-secrets","readOnly":true},{"mountPath":"/var/jenkins_cache","name":"jenkins-cache"},{"mountPath":"/tmp","name":"tmp-volume"},{"mountPath":"/etc/ssl/certs/ca-certificates.crt","name":"ca-certificates","subPath":"ca-certificates.crt"}]},{"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"LABEL","value":"jenkins-jenkins-config"},{"name":"FOLDER","value":"/var/jenkins_home/casc_configs"},{"name":"NAMESPACE","value":"jenkins"},{"name":"REQ_URL","value":"http://localhost:8080/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)"},{"name":"REQ_METHOD","value":"POST"},{"name":"REQ_RETRY_CONNECT","value":"10"}],"image":"docker.io/kiwigrid/k8s-sidecar:1.30.7","imagePullPolicy":"IfNotPresent","name":"config-reload","resources":{},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/jenkins_home/casc_configs","name":"sc-config-volume"},{"mountPath":"/var/jenkins_home","name":"jenkins-home"}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":false,"initContainers":[{"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"LABEL","value":"jenkins-jenkins-config"},{"name":"FOLDER","value":"/var/jenkins_home/casc_configs"},{"name":"NAMESPACE","value":"jenkins"},{"name":"METHOD","value":"LIST"}],"image":"docker.io/kiwigrid/k8s-sidecar:1.30.7","imagePullPolicy":"IfNotPresent","name":"config-reload-init","resources":{},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/jenkins_home/casc_configs","name":"sc-config-volume"},{"mountPath":"/var/jenkins_home","name":"jenkins-home"}]},{"command":["sh","/var/jenkins_config/apply_config.sh"],"image":"harbor.lab.local/jenkins/maven-agent:17","imagePullPolicy":"Always","name":"init","resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"50m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true,"runAsGroup":1000,"runAsUser":1000},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/jenkins_home","name":"jenkins-home"},{"mountPath":"/var/jenkins_config","name":"jenkins-config"},{"mountPath":"/usr/share/jenkins/ref/plugins","name":"plugins"},{"mountPath":"/var/jenkins_plugins","name":"plugin-dir"},{"mountPath":"/tmp","name":"tmp-volume"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"runAsNonRoot":true,"runAsUser":1000,"supplementalGroups":[1000]},"serviceAccount":"jenkins","serviceAccountName":"jenkins","terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"plugins"},{"configMap":{"defaultMode":420,"name":"jenkins"},"name":"jenkins-config"},{"emptyDir":{},"name":"plugin-dir"},{"name":"jenkins-secrets","projected":{"defaultMode":420,"sources":[{"secret":{"items":[{"key":"jenkins-admin-user","path":"chart-admin-username"},{"key":"jenkins-admin-password","path":"chart-admin-password"}],"name":"jenkins"}}]}},{"name":"ingress-ca","secret":{"defaultMode":420,"secretName":"ingress-ca"}},{"configMap":{"defaultMode":420,"items":[{"key":"ca-certificates.crt","path":"ca-certificates.crt"}],"name":"jenkins-ca-cert"},"name":"ca-certificates"},{"emptyDir":{},"name":"jenkins-cache"},{"name":"jenkins-home","persistentVolumeClaim":{"claimName":"jenkins"}},{"emptyDir":{},"name":"sc-config-volume"},{"emptyDir":{},"name":"tmp-volume"}]}},"updateStrategy":{"rollingUpdate":{"partition":0},"type":"RollingUpdate"}},"status":{"availableReplicas":0,"collisionCount":0,"currentRevision":"jenkins-7b949cd55","observedGeneration":3,"replicas":1,"updateRevision":"jenkins-6f45d6f8cc","updatedReplicas":1}}
    meta.helm.sh/release-name: jenkins
    meta.helm.sh/release-namespace: jenkins
  creationTimestamp: "2026-01-21T03:09:22Z"
  generation: 4
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-5.8.115
  name: jenkins
  namespace: jenkins
  resourceVersion: "7354940"
  uid: 37cbc16f-3bb0-49e9-8fe3-e7792e967c9e
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: jenkins-controller
      app.kubernetes.io/instance: jenkins
  serviceName: jenkins
  template:
    metadata:
      annotations:
        checksum/config: f93b0dce2d1985a938deaddcec93eb3b695745dc7790dcb961329173f7b48051
        kubectl.kubernetes.io/restartedAt: "2026-01-21T02:36:02Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: jenkins-controller
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: jenkins
        helm.sh/chart: jenkins-5.8.115
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --httpPort=8080
        env:
        - name: SECRETS
          value: /run/secrets/additional
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: JAVA_OPTS
          value: '-Dcasc.reload.token=$(POD_NAME) '
        - name: JENKINS_OPTS
          value: '--webroot=/var/jenkins_cache/war '
        - name: JENKINS_SLAVE_AGENT_PORT
          value: "50000"
        - name: CASC_JENKINS_CONFIG
          value: /var/jenkins_home/casc_configs
        image: harbor.lab.local/jenkins/maven-agent:17
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: agent-listener
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsUser: 1000
        startupProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
          readOnly: true
        - mountPath: /usr/share/jenkins/ref/plugins/
          name: plugin-dir
        - mountPath: /var/jenkins_home/casc_configs
          name: sc-config-volume
        - mountPath: /run/secrets/additional
          name: jenkins-secrets
          readOnly: true
        - mountPath: /var/jenkins_cache
          name: jenkins-cache
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ca-certificates
          subPath: ca-certificates.crt
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: LABEL
          value: jenkins-jenkins-config
        - name: FOLDER
          value: /var/jenkins_home/casc_configs
        - name: NAMESPACE
          value: jenkins
        - name: REQ_URL
          value: http://localhost:8080/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)
        - name: REQ_METHOD
          value: POST
        - name: REQ_RETRY_CONNECT
          value: "10"
        image: docker.io/kiwigrid/k8s-sidecar:1.30.7
        imagePullPolicy: IfNotPresent
        name: config-reload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home/casc_configs
          name: sc-config-volume
        - mountPath: /var/jenkins_home
          name: jenkins-home
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      initContainers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: LABEL
          value: jenkins-jenkins-config
        - name: FOLDER
          value: /var/jenkins_home/casc_configs
        - name: NAMESPACE
          value: jenkins
        - name: METHOD
          value: LIST
        image: docker.io/kiwigrid/k8s-sidecar:1.30.7
        imagePullPolicy: IfNotPresent
        name: config-reload-init
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home/casc_configs
          name: sc-config-volume
        - mountPath: /var/jenkins_home
          name: jenkins-home
      - command:
        - sh
        - /var/jenkins_config/apply_config.sh
        image: harbor.lab.local/jenkins/maven-agent:17
        imagePullPolicy: Always
        name: init
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
        - mountPath: /usr/share/jenkins/ref/plugins
          name: plugins
        - mountPath: /var/jenkins_plugins
          name: plugin-dir
        - mountPath: /tmp
          name: tmp-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        supplementalGroups:
        - 1000
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: plugins
      - configMap:
          defaultMode: 420
          name: jenkins
        name: jenkins-config
      - emptyDir: {}
        name: plugin-dir
      - name: jenkins-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: jenkins-admin-user
                path: chart-admin-username
              - key: jenkins-admin-password
                path: chart-admin-password
              name: jenkins
      - name: ingress-ca
        secret:
          defaultMode: 420
          secretName: ingress-ca
      - configMap:
          defaultMode: 420
          items:
          - key: ca-certificates.crt
            path: ca-certificates.crt
          name: jenkins-ca-cert
        name: ca-certificates
      - emptyDir: {}
        name: jenkins-cache
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins
      - emptyDir: {}
        name: sc-config-volume
      - emptyDir: {}
        name: tmp-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 0
  collisionCount: 0
  currentRevision: jenkins-7b949cd55
  observedGeneration: 4
  replicas: 1
  updateRevision: jenkins-547bff58b7
