apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: cicd123
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cicd123
  policy:
    numerical:
      order: asc
  digestReflectionPolicy: Never
