pipeline {
  agent any

  environment {
    REGISTRY = "harbor.lab.local"
    IMAGE = "demo/python-app"
    TAG = "${BUILD_NUMBER}"
    SONAR_HOST = "http://sonarqube.sonarqube.svc.cluster.local:9000"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('SonarQube Scan') {
      steps {
        withSonarQubeEnv('sonarqube') {
          sh '''
            sonar-scanner \
              -Dsonar.projectKey=my-python-project \
              -Dsonar.sources=app \
              -Dsonar.host.url=$SONAR_HOST
          '''
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        sh "docker build -t $REGISTRY/$IMAGE:$TAG ."
      }
    }

    stage('Push Image to Harbor') {
      steps {
        sh "docker push $REGISTRY/$IMAGE:$TAG"
      }
    }

    stage('Trivy Scan') {
      steps {
        sh "trivy image --exit-code 1 --severity CRITICAL $REGISTRY/$IMAGE:$TAG"
      }
    }

    stage('Update Kubernetes Manifests') {
      steps {
        sh '''
          sed -i "s|image:.*|image: $REGISTRY/$IMAGE:$TAG|" k8s/deployment.yaml
          git commit -am "Update image to $TAG"
          git push
        '''
      }
    }
  }
}

