apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-reflector-controller
rules:
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources: ["imagerepositories"]
    verbs: ["get", "list", "watch"]
